- hosts: all
  become: true
  tasks:

  - name: create simone user
    tags: always
    user:
      name: simone
      groups: sudo

  - name: add ssh key for simone
    tags: always
    authorized_key:
      user: simone
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIN8QGwHfse1WdGantsXzA9dxCmvC/yQHdTlFM++D3irC root@c1-ansible"
  - name: add sudoers file for ansible
    tags: always
    copy:
      src: sudoer_simone
      dest: /etc/sudoers.d/simone
      owner: root
      group: root
      mode: 0440