---

- hosts: c1-cp1.local
  become: true
  become_user: root
  tasks:

  - name: create simone user
    tags: always
    ansible.builtin.user:
      name: simone
      uid: 1002
      gid: 1002
      group: sudo

