---
- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: true      
    when: ansible_distribution == "Ubuntu"
    
  - name: install apache2 and php support packages
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"