---
- hosts: all
  become: true
  pre_tasks:

  - name: install updates (CentOS)
    tags: always
    dnf:
      update_only: true
      update_cache: true
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: true
    when: ansible_distribution == "Ubuntu"

- hosts: worker_nodes
  become: true     
  tasks:
  
  - name: remove apache2 and php support packages
    tags: apache, apache2, ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: absent
    when: ansible_distribution == "Ubuntu"

  - name: remove apache and php packages for CentOS
    tags: httpd, apache, centos
    dnf:
      name:
        - httpd
        - php
      state: absent
    when: ansible_distribution == "CentOS"

- hosts: control_nodes
  become: true
  tasks:

  - name: remove apache2 and php support packages
    tags: apache, apache2, ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: absent
    when: ansible_distribution == "Ubuntu"

  - name: remove apache and php packages for CentOS
    tags: httpd, apache, centos
    dnf:
      name:
        - httpd
        - php
      state: absent
    when: ansible_distribution == "CentOS"

