---
- hosts: control_nodes
  become: true
  pre_tasks:

  - name: install updates (CentOS)
    tags: always
    dnf:
      update_only: true
      update_cache: true
    when: ansible_distribution == "CentOS"

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: true
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  tasks:

  - name: create simone user
    tags: always
    user:
      name: simone
      groups: root

  - name: add ssh keys for simone
    tags: always
    authorized_key:
      user: simone
      key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC7NNfbaqVQtf+zgUATW7pyAY8Y+E5GFzs020COHzZZUBYhfMtMeAsK/2PclijPQGgpu4SEuAXbbmTnDh93nvoDdbsP+izqg/2d9l/LpiZhzxevKGukHEMDpZ19B0KH9O4WcsxCSPJgDOCdDS8ro7oOAmucToBxNd3oQIGYptIAdan0q4wPE45vy+qMqSAbiPhIoMNVmEdUwP6xxoSOivSHp1OLDkuN9wGxyhQ4PwZBbL0R0yoS5vxDx23L08yqgTtdprXi04bt/xpYCbTq6bGxpLk24lOrlJxe4VSuXBwWbMjQe90UUH0jA6zL9m7rf60qvft6lq7zXT3H+wGXkpbhe6sPKjdo7Jsf/pIAk6Fsba43jDBBzaFyrF8xHOEiTNwG2LqKZG24ES82VYzRp4pxjNegWL1UNwmjuWukU+hpUorDxfyYgOtW+twO0DeU/REZU6hfW6HRFeBt0lLYzd8z9pYc9NdJn2Sj77Mh0DB0JpMYreVgQyj/ffB9uN8YVb8= root@c1-ansible"

  - name: add sudoers file for ansible
    tags: always
    copy:
      src: sudoer_simone
      dest: /etc/sudoers.d/simone
      owner: root
      group: root
      mode: 0440

- hosts: worker_nodes
  become: true     
  tasks:

  - name: install apache2 and php support packages
    tags: apache, apache2, ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php packages (CentOS)
    tags: httpd, php, centos
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"
   
  - name: start httpd service (CentOS)
    tags: apache,centos,httpd
    service: 
      name: httpd
      state: started
      enabled: true
    when: ansible_distribution == "CentOS"  

  - name: change e-mail address for admin (CentOS)
    tags: apache,centos,httpd
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin somebody@somewhere.net
    when: ansible_distribution == "CentOS"
    register: httpd       

  - name: restart httpd service (CentOS)
    tags: apache,centos,httpd
    service: 
      name: httpd
      state: restarted
    when: httpd.changed
   
  - name: copy default html file for site
    tags: apache, apache2, httpd
    copy:
       src: default_site.html
       dest: /var/www/html/index.html
       owner: root
       group: root
       mode: 0644

- hosts: workstations
  become: true
  tasks:

  - name: install unzip packages
    package:
      name: unzip

  - name: install terraform packages
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.3.9/terraform_1.3.9_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

